import type { Metadata } from 'next';

import { Geist, Geist_Mono } from 'next/font/google';

import { getServerSession } from 'next-auth';
import { Toaster } from 'sonner';

import './globals.css';
import { QueryProvider } from '@/providers/query-client-provider';
import 'mapbox-gl/dist/mapbox-gl.css';
import { SessionProvider } from '@/providers/session-provider';

import { authOptions } from './api/auth/[...nextauth]/route';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'SkyAware App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider session={session}>
          <QueryProvider>
            <div>{children}</div>
          </QueryProvider>
        </SessionProvider>
        <Toaster position='top-right' richColors />
      </body>
    </html>
  );
}
