steps:
  # Retrieve secrets from Secret Manager
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud secrets versions access latest --secret=earthdata-username > /workspace/earthdata_username.txt
        gcloud secrets versions access latest --secret=earthdata-password > /workspace/earthdata_password.txt
        gcloud secrets versions access latest --secret=db-password > /workspace/db_password.txt

  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/tempo-pipeline:$COMMIT_SHA', '.']

  # Push the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/tempo-pipeline:$COMMIT_SHA']

  # Deploy to Cloud Run (pipeline)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'tempo-pipeline'
      - '--image'
      - 'gcr.io/$PROJECT_ID/tempo-pipeline:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'EARTHDATA_USERNAME=$(cat /workspace/earthdata_username.txt),EARTHDATA_PASSWORD=$(cat /workspace/earthdata_password.txt),DB_HOST=${_DB_HOST},DB_PORT=${_DB_PORT},DB_USER=${_DB_USER},DB_PASS=$(cat /workspace/db_password.txt),DB_NAME=${_DB_NAME},REDIS_HOST=${_REDIS_HOST},REDIS_PORT=${_REDIS_PORT}'

  # Deploy endpoint to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'tempo-endpoint'
      - '--image'
      - 'gcr.io/$PROJECT_ID/tempo-pipeline:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'DB_HOST=${_DB_HOST},DB_PORT=${_DB_PORT},DB_USER=${_DB_USER},DB_PASS=$(cat /workspace/db_password.txt),DB_NAME=${_DB_NAME},REDIS_HOST=${_REDIS_HOST},REDIS_PORT=${_REDIS_PORT}'
      - '--command'
      - 'gunicorn'
      - '--bind'
      - ':8080'
      - 'endpoint:app'