steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/tempo-pipeline:$COMMIT_SHA', '.']

  # Push the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/tempo-pipeline:$COMMIT_SHA']

  # Deploy to Cloud Run (pipeline)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'tempo-pipeline'
      - '--image'
      - 'gcr.io/$PROJECT_ID/tempo-pipeline:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'EARTHDATA_USERNAME=${_EARTHDATA_USERNAME},EARTHDATA_PASSWORD=${_EARTHDATA_PASSWORD},DB_HOST=${_DB_HOST},DB_PORT=${_DB_PORT},DB_USER=${_DB_USER},DB_PASS=${_DB_PASS},DB_NAME=${_DB_NAME},REDIS_HOST=${_REDIS_HOST},REDIS_PORT=${_REDIS_PORT},REDIS_PASSWORD=${_REDIS_PASSWORD}'

  # Deploy endpoint to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'tempo-endpoint'
      - '--image'
      - 'gcr.io/$PROJECT_ID/tempo-pipeline:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'DB_HOST=${_DB_HOST},DB_PORT=${_DB_PORT},DB_USER=${_DB_USER},DB_PASS=${_DB_PASS},DB_NAME=${_DB_NAME},REDIS_HOST=${_REDIS_HOST},REDIS_PORT=${_REDIS_PORT},REDIS_PASSWORD=${_REDIS_PASSWORD}'
      - '--command'
      - 'gunicorn'
      - '--bind'
      - ':8080'
      - 'endpoint:app'